title: Backend Engineering Bootcamp Handbook
description: A practical backend-focused engineering onboarding handbook for interns.

baseurl: "/engineering-bootcamp-handbook"
url: "https://indapmgr.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false

plugins:
  - jekyll-seo-tag
